# Example: Test-only pipeline for feature branches
# This example shows how to run only tests without building or deploying

name: Feature Branch Validation

on:
  push:
    branches: ["feature/*", "bugfix/*", "hotfix/*"]
  pull_request:
    branches: [main, develop]

jobs:
  validate:
    name: Validate Changes
    uses: Traventia/ci-templates/.github/workflows/ts-srv-cicd.yml@main
    with:
      # Only run tests, skip build and deploy
      skip_build: true
      skip_deploy: true

      # Use staging environment for app identification
      environment: "staging"

      # Use latest Node.js LTS
      node_version: "20.x"
    secrets:
      # Only AWS secrets needed for downloading ci-scripts
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_CI_BUCKET_REGION: ${{ secrets.AWS_CI_BUCKET_REGION }}
      AWS_CI_BUCKET: ${{ secrets.AWS_CI_BUCKET }}

      # NPM token for installing private packages
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
